refactoring predict
fizdm/VILearn pull request #11
Opened 2023-07-23 11:30 UTC by MaxxximOchka

2023-07-23 11:40 UTC, FizzyShow requested changes
Идея была в том, чтобы в класс NeuralNetwork добавить реализацию метода predict, вместо текущего проксирования

2023-07-23 11:40 UTC, FizzyShow commented on nn/layer_functions/__init__.py
> +from PolitechLastShot.nn.layer_functions.relu import RELU
Смысл изменений?

2023-07-23 11:42 UTC, MaxxximOchka commented on nn/layer_functions/__init__.py
> +from PolitechLastShot.nn.layer_functions.relu import RELU
Не работали изначальные пути, заменил

2023-07-23 11:44 UTC, FizzyShow commented on nn/layer_functions/__init__.py
> +from PolitechLastShot.nn.layer_functions.relu import RELU
Так делать не надо, теряется какая-либо гибкость структуры. Если тестировать через playbook питоновский, то все должно работать

2023-07-23 11:52 UTC, MaxxximOchka commented on nn/layer_functions/__init__.py
> +from PolitechLastShot.nn.layer_functions.relu import RELU
хорошо, исправлю

2023-07-26 17:36 UTC, FizzyShow requested changes
В целом, пункт с вынесом predict верный. Осталось сделать слой, который бы после прямого распросранения превращал результат в тип, который в датасете, в идеале это бы встроить в процедуру прямого распространения.

То есть, чтобы это работало так:
```
layers = [
inner,
Rely,
sigmoid,
converter_to_datasettype
```

должен быть слоем и наследоваться от ILayer

2023-07-26 17:36 UTC, FizzyShow commented on nn/optimizers/SGD.py
>      def predict(self, X):
Здесь предикт вообще не нужен

2023-07-26 17:36 UTC, FizzyShow commented on nn/layer_functions/__init__.py
> +from PolitechLastShot.nn.layer_functions.relu import RELU
Не увидел

2023-11-13 06:57 UTC, fizdm approved these changes

2023-11-13 06:57 UTC, merged